-- ToonScripture OS Supabase schema
-- This schema mirrors the current local SQLite model so the hosted app can use persistent cloud storage.

create extension if not exists pgcrypto;

create table if not exists public.projects (
  id text primary key,
  story_name text not null,
  bible_reference text,
  target_minutes double precision default 6,
  format text default 'long_form',
  status text default 'idea',
  treatment_json jsonb,
  script_json jsonb,
  critique_json jsonb,
  character_bible_json jsonb,
  scenes_json jsonb,
  package_json jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.catalog_people (
  id text primary key,
  source_sheet text,
  source_position integer,
  testament text,
  book text,
  name text not null,
  entity_type text,
  named_status text,
  bible_references text,
  story_role text,
  priority text,
  cinematic_score double precision,
  youtube_hook text,
  reference_asset_need text,
  primary_environment text,
  canon text,
  playlist_series text,
  notes text,
  source_url text,
  imported_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.catalog_series (
  id text primary key,
  rank integer,
  series_name text unique not null,
  series_type text,
  core_concept text,
  best_starter_episodes text,
  youtube_reason text,
  recommended_scene_count text,
  recommended_runtime text,
  priority text,
  status text,
  source_notes text,
  imported_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.project_catalog_links (
  project_id text primary key references public.projects(id) on delete cascade,
  catalog_person_id text references public.catalog_people(id) on delete set null,
  catalog_series_id text references public.catalog_series(id) on delete set null,
  episode_title text,
  created_at timestamptz default now()
);

create table if not exists public.references_library (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  reference_type text not null,
  name text not null,
  status text default 'not_approved',
  master_prompt text,
  identity_lock text,
  negative_lock text,
  image_path text,
  metadata_json jsonb,
  updated_at timestamptz default now(),
  unique(project_id, reference_type, name)
);

create index if not exists idx_catalog_people_name on public.catalog_people(name);
create index if not exists idx_catalog_people_priority on public.catalog_people(priority);
create index if not exists idx_catalog_people_series on public.catalog_people(playlist_series);
create index if not exists idx_projects_created_at on public.projects(created_at desc);

alter table public.projects enable row level security;
alter table public.catalog_people enable row level security;
alter table public.catalog_series enable row level security;
alter table public.project_catalog_links enable row level security;
alter table public.references_library enable row level security;

-- ToonScripture is currently a private single-user production tool.
-- Server-side app access should use the Supabase service role key.


create table if not exists public.project_assets (
  id uuid primary key default gen_random_uuid(),
  project_id text not null references public.projects(id) on delete cascade,
  asset_type text not null,
  name text not null,
  storage_path text not null,
  metadata_json jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.episode_metrics (
  id uuid primary key default gen_random_uuid(),
  project_id text not null references public.projects(id) on delete cascade,
  views bigint,
  impressions bigint,
  ctr double precision,
  average_view_duration_seconds integer,
  average_percentage_viewed double precision,
  subscribers_gained integer,
  notes text,
  recorded_at timestamptz default now()
);

create index if not exists idx_project_assets_project
  on public.project_assets(project_id);

create index if not exists idx_project_assets_type
  on public.project_assets(project_id, asset_type);

create index if not exists idx_episode_metrics_project
  on public.episode_metrics(project_id, recorded_at desc);

-- Runtime access is protected by authenticated-admin RLS policies
-- applied to the connected Supabase project.

-- -------------------------------------------------------------------
-- Story Catalog Architect
-- Separates character records from production stories and episodes.
-- -------------------------------------------------------------------

create table if not exists public.catalog_stories (
  id text primary key,
  story_key text unique not null,
  story_title text not null,
  testament text,
  book text,
  bible_references text,
  story_summary text,
  episode_count integer not null default 1 check (episode_count between 1 and 3),
  structure_type text not null default 'single',
  structure_reason text,
  ai_structure_status text not null default 'analyzed',
  human_override boolean not null default false,
  analysis_json jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.catalog_story_people (
  story_id text not null references public.catalog_stories(id) on delete cascade,
  catalog_person_id text not null references public.catalog_people(id) on delete cascade,
  relationship_role text,
  is_primary boolean not null default false,
  created_at timestamptz default now(),
  primary key (story_id, catalog_person_id)
);

create table if not exists public.catalog_episodes (
  id text primary key,
  story_id text not null references public.catalog_stories(id) on delete cascade,
  episode_number integer not null check (episode_number between 1 and 3),
  episode_title text not null,
  display_title text not null,
  bible_reference text,
  narrative_scope text,
  hook text,
  conflict text,
  climax text,
  resolution text,
  recommended_runtime_minutes double precision,
  status text not null default 'planned',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (story_id, episode_number)
);

alter table public.project_catalog_links
  add column if not exists catalog_story_id text references public.catalog_stories(id) on delete set null;

alter table public.project_catalog_links
  add column if not exists catalog_episode_id text references public.catalog_episodes(id) on delete set null;

create index if not exists idx_catalog_story_people_person
  on public.catalog_story_people(catalog_person_id);

create index if not exists idx_catalog_episodes_story
  on public.catalog_episodes(story_id, episode_number);

create index if not exists idx_project_catalog_links_story
  on public.project_catalog_links(catalog_story_id);

create index if not exists idx_project_catalog_links_episode
  on public.project_catalog_links(catalog_episode_id);

alter table public.catalog_stories enable row level security;
alter table public.catalog_story_people enable row level security;
alter table public.catalog_episodes enable row level security;

grant select, insert, update, delete on public.catalog_stories to authenticated, service_role;
grant select, insert, update, delete on public.catalog_story_people to authenticated, service_role;
grant select, insert, update, delete on public.catalog_episodes to authenticated, service_role;

drop policy if exists "toonscripture admin catalog stories" on public.catalog_stories;
create policy "toonscripture admin catalog stories"
on public.catalog_stories
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "toonscripture admin story people" on public.catalog_story_people;
create policy "toonscripture admin story people"
on public.catalog_story_people
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "toonscripture admin catalog episodes" on public.catalog_episodes;
create policy "toonscripture admin catalog episodes"
on public.catalog_episodes
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);
