-- ToonScripture OS Supabase schema
-- This schema mirrors the current local SQLite model so the hosted app can use persistent cloud storage.

create extension if not exists pgcrypto;

create table if not exists public.projects (
  id text primary key,
  story_name text not null,
  bible_reference text,
  target_minutes double precision default 6,
  format text default 'long_form',
  status text default 'idea',
  treatment_json jsonb,
  script_json jsonb,
  critique_json jsonb,
  character_bible_json jsonb,
  scenes_json jsonb,
  package_json jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.catalog_people (
  id text primary key,
  source_sheet text,
  source_position integer,
  testament text,
  book text,
  name text not null,
  entity_type text,
  named_status text,
  bible_references text,
  story_role text,
  priority text,
  cinematic_score double precision,
  youtube_hook text,
  reference_asset_need text,
  primary_environment text,
  canon text,
  playlist_series text,
  notes text,
  source_url text,
  imported_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.catalog_series (
  id text primary key,
  rank integer,
  series_name text unique not null,
  series_type text,
  core_concept text,
  best_starter_episodes text,
  youtube_reason text,
  recommended_scene_count text,
  recommended_runtime text,
  priority text,
  status text,
  source_notes text,
  imported_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.project_catalog_links (
  project_id text primary key references public.projects(id) on delete cascade,
  catalog_person_id text references public.catalog_people(id) on delete set null,
  catalog_series_id text references public.catalog_series(id) on delete set null,
  episode_title text,
  created_at timestamptz default now()
);

create table if not exists public.references_library (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  reference_type text not null,
  name text not null,
  status text default 'not_approved',
  master_prompt text,
  identity_lock text,
  negative_lock text,
  image_path text,
  metadata_json jsonb,
  updated_at timestamptz default now(),
  unique(project_id, reference_type, name)
);

create index if not exists idx_catalog_people_name on public.catalog_people(name);
create index if not exists idx_catalog_people_priority on public.catalog_people(priority);
create index if not exists idx_catalog_people_series on public.catalog_people(playlist_series);
create index if not exists idx_projects_created_at on public.projects(created_at desc);

alter table public.projects enable row level security;
alter table public.catalog_people enable row level security;
alter table public.catalog_series enable row level security;
alter table public.project_catalog_links enable row level security;
alter table public.references_library enable row level security;

-- ToonScripture is currently a private single-user production tool.
-- Server-side app access should use the Supabase service role key.
